version: '3'
services:
 transmission:
  image: haugene/transmission-openvpn
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - "9091:9091"
    # - "8888:8888" # proxy support
  volumes:
    - /media/sdb1/:/data # where transmission will store the data
    - /path/to/data:/config # where transmission-home is stored
    - /media/sdb1/:/downloads
  environment:
    - OPENVPN_PROVIDER=fastvpn
    - OPENVPN_USERNAME=ncpxzatrox@namecheap
    - OPENVPN_PASSWORD=r7aJe5PBAQ
    - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    - LOCAL_NETWORK=10.0.0.0/24
    - TRANSMISSION_RPC_USERNAME=Trox
    - TRANSMISSION_RPC_PASSWORD=Zxcvbnm1983
    - TRANSMISSION_RPC_AUTHENTICATION_REQUIRED=true
    - TRANSMISSION_HOME=/config
    - GITHUB_CONFIG_SOURCE_REPO=Xzatrox/vpn-configs-contrib
 # proxy:
 #  image: haugene/transmission-openvpn-proxy
 #  links:
 #    - transmission
 #  ports:
 #    - 8080:8080
 #  volumes:
 #    - /etc/localtime:/etc/localtime:ro

 # rss:
 #  image: haugene/transmission-rss
 #  links:
 #    - transmission
 #  environment:
 #    - RSS_URL=http://.../xxxxx.rss
